# Generated by Django 5.2.9 on 2025-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('CE', 'Computer Engineering'), ('ARCH', 'Architecture'), ('CIVIL', 'Civil Engineering'), ('ECE', 'Electronics, Communication & Information Engineering'), ('EE', 'Electrical Engineering')], max_length=5)),
                ('batch', models.CharField(help_text='Example: 079 Batch', max_length=20)),
                ('photo', models.ImageField(help_text='Upload JPG or PNG image', upload_to='team_photos/')),
                ('position_order', models.PositiveIntegerField(help_text='Lower number appears first (1 = President)')),
                ('profile_file', models.FileField(blank=True, help_text='Upload CV or related file (optional)', null=True, upload_to='team_files/')),
                ('profile_link', models.URLField(blank=True, help_text='External profile or portfolio link (optional)', null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position_order'],
            },
        ),
    ]
