# Generated by Django 5.2.9 on 2026-02-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='Example: member@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Example: +977-98XXXXXXXX', max_length=25, null=True),
        ),
    ]
