# Generated by Django 5.2.9 on 2025-12-19 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('total_time_of_event', models.DurationField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('register_form', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventInfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('file_link', models.URLField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='events.event')),
            ],
        ),
    ]
