# Generated by Django 5.2.9 on 2025-12-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
