# Generated by Django 5.2.9 on 2025-12-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_time_of_event',
            field=models.TextField(),
        ),
    ]
