# Generated by Django 5.2.9 on 2026-05-17 15:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='file',
            field=models.FileField(help_text='Upload PDF, DOCX, ZIP', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='learning_resources/'),
        ),
        migrations.AlterField(
            model_name='workshopresource',
            name='file',
            field=models.FileField(help_text='Upload PDF, DOCX, ZIP', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='workshop_resources/'),
        ),
    ]
