# Generated by Django 5.2.9 on 2025-12-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Users',
        ),
    ]
