"""
Django settings for robotics_club project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# ==============================================================================
# 1. CORE PATHS & ENVIRONMENT CONFIGURATION
# ==============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment file if it exists, fallback to system environment variables on Railway
env_path = BASE_DIR / '.env.local'
if env_path.exists():
    load_dotenv(dotenv_path=env_path)
else:
    load_dotenv()

# ==============================================================================
# 2. SECURITY & ENVIRONMENT SETTINGS
# ==============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^9nv#!duef6z+j@9jisbggtxlwo(oyyv1cjbx%kt4#__1(4nc$')

# SECURITY WARNING: don't run with debug turned on in production!
# Change this to True temporarily to find our bug
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://*.railway.app"
]

# ==============================================================================
# 3. APPLICATION & MIDDLEWARE DEFINITIONS
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    # Custom local apps
    'accounts',
    'core',
    'anymail',
    'events',
    'teams',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Handles efficient static asset delivery
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'robotics_club.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'robotics_club.wsgi.application'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# ==============================================================================
# 4. DATABASE SELECTION LAYOUT
# ==============================================================================
DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    # Production Infrastructure: Managed Cloud Database Connection (Railway)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local Infrastructure: Failover Offline Lightweight Database (SQLite)
    print("WARNING: DATABASE_URL not detected. Falling back to local SQLite.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==============================================================================
# 5. AUTHENTICATION & ACCESS ROUTING
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 2 Weeks expiration window
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ==============================================================================
   # 6. STATIC AND MEDIA ASSETS CONFIGURATION
   # ==============================================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

   # Check environment status to determine media storage engine type
if os.environ.get('DATABASE_URL'):
    # PRODUCTION: Offload all user uploads securely to Cloudinary permanent cloud storage
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
        'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    }
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.RawMediaCloudinaryStorage"
    MEDIA_URL = '/media/'
else:
    # LOCAL DEVELOPMENT: Save locally to your computer's hard drive
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==============================================================================
# 7. INTERNATIONALIZATION & SYSTEM TIMING
# ==============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'
USE_I18N = True
USE_TZ = False

# Add this block to your settings.py
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.RawMediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ==============================================================================
# 8. EMAIL DISPATCH SYSTEM ARCHITECTURE (BREVO API DRIVEN)
# ==============================================================================
ADMIN_EMAIL = "aadityajoshi600@gmail.com"  # 👈 This must be your Brevo login email

if os.environ.get('DATABASE_URL'):
    # PRODUCTION SETTINGS (Railway): Sends real emails to ANYONE via Brevo API
    EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
    ANYMAIL = {
        "SENDINBLUE_API_KEY": os.environ.get("BREVO_API_KEY"),
    }
    DEFAULT_FROM_EMAIL = f"Robotics Club <{ADMIN_EMAIL}>"
    DEBUG = False 
else:
    # LOCAL SETTINGS (Your computer): Prints emails to the terminal console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = ADMIN_EMAIL
    DEBUG = True