"""
Django settings for robotics_club project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# ==============================================================================
# 1. CORE PATHS & ENVIRONMENT CONFIGURATION
# ==============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment file if it exists, fallback to system environment variables on Railway
env_path = BASE_DIR / '.env.local'
if env_path.exists():
    load_dotenv(dotenv_path=env_path)
else:
    load_dotenv()

# ==============================================================================
# 2. SECURITY & ENVIRONMENT SETTINGS
# ==============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^9nv#!duef6z+j@9jisbggtxlwo(oyyv1cjbx%kt4#__1(4nc$')

# SECURITY WARNING: don't run with debug turned on in production!
# Automatically turns off DEBUG mode if running on Railway production
DEBUG = os.environ.get('RAILWAY_ENVIRONMENT') is None

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://*.railway.app"
]

# ==============================================================================
# 3. APPLICATION & MIDDLEWARE DEFINITIONS
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom local apps
    'accounts',
    'core',
    'events',
    'teams',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Handles efficient static asset delivery
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'robotics_club.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'robotics_club.wsgi.application'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# ==============================================================================
# 4. DATABASE SELECTION LAYOUT
# ==============================================================================
DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    # Production Infrastructure: Managed Cloud Database Connection (Railway)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local Infrastructure: Failover Offline Lightweight Database (SQLite)
    print("WARNING: DATABASE_URL not detected. Falling back to local SQLite.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==============================================================================
# 5. AUTHENTICATION & ACCESS ROUTING
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 2 Weeks expiration window
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ==============================================================================
# 6. STATIC AND MEDIA ASSETS CONFIGURATION
# ==============================================================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# 7. INTERNATIONALIZATION & SYSTEM TIMING
# ==============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'
USE_I18N = True
USE_TZ = False

# ==============================================================================
# 8. EMAIL DISPATCH SYSTEM ARCHITECTURE
# ==============================================================================
ADMIN_EMAIL = "aadityajoshi600@gmail.com"

# Check environment state to determine real vs console email distribution routing
if DATABASE_URL:
    # Live Production SMTP Layout (Dispatches authentic emails to external inboxes)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    
    # Read secure values out of Railway Variables dashboard, with secure hardcoded defaults
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'aadityajoshi600@gmail.com')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'lyjmyvrtchwqhswi')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    # Sandbox Development Layout (Prints output to local terminal, saving bandwidth and preventing crashes)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'test@robotics_club.local'